### ISSUE TITLE
Error using p5-embedder in Wordpress 4.2.3

### ISSUE THREAD

**Issue by golanlevin** [lmccart/p5.js-wp-embedder#4]
Hi, 
Installing and activating the p5 plugin in a fresh install of Wordpress 4.2.3 produces the following error, reported multiple times at the top of each page:

Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Empty string supplied as input in /nfs/c05/h06/mnt/77459/domains/cmuems.com/html/2015c/wp-content/plugins/p5-embedder/p5-embedder.php on line 48

You can see how this looks here: 
http://cmuems.com/2015c/

Please help if you can! I'm really looking forward to using p5.js this fall :)

**Comment by golanlevin** [comment]
So, some more information. It turns out the bug's effects are mostly cosmetic. As you can see from the following example, the p5.js embedder "works", but reports some unattractive errors at the top of the page: http://cmuems.com/2015c/resources/embedding-p5-js/. 

Thanks for any help with this!

**Comment by golanlevin** [comment]
OK, I found a fix :) Now will learn how to post a pull request.

**Comment by lmccart** [comment]
Ah, you beat me to it! Ok let me know if you need any help with the PR, thanks for figuring this out!

**Comment by golanlevin** [comment]
Hi Lauren, 
It turns out my very crude fix to the WP embedder is causing all sorts of side-effects that impair the proper functioning of the Wordpress engine throughout the site. My fix is no good. 

Essentially I said that if the input is empty then just return null. But I think something else must need to happen. When I reactivated the plugin, Wordpress reported the following: 

*The plugin generated 3 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.*

Sorry :( !

**Comment by lmccart** [comment]
no worries, thanks for trying! I'll take a look tomorrow evening.

**Comment by golanlevin** [comment]
Thanks Lauren!

My "fix" is pretty awful, seriously impairing basic operations like making and saving new posts. I received the following error: 

Warning: Cannot modify header information - headers already sent by (output started at /nfs/c05/h06/mnt/77459/domains/cmuems.com/html/2015c/wp-content/plugins/p5-embedder/p5-embedder.php:99) in /nfs/c05/h06/mnt/77459/domains/cmuems.com/html/2015c/wp-includes/pluggable.php on line 1196

Brutal.
