### ISSUE TITLE
Double-ampersands (&&) cause catastrophic display error

### ISSUE THREAD

**Issue by golanlevin** [lmccart/p5.js-wp-embedder#9]
It turns out that using <code>&&</code> can cause a catastrophic display failure when the Embedder attempts to typeset the p5.js code. 

For an example: here is a program made by a student. I have removed his && characters (and replaced them with nested if blocks) so that the sketch and code will display correctly: http://cmuems.com/2015c/admin/10/17/dfrank-project-7/ 

However, here is the student's original project, and his attempt to embed it in the Wordpress. Note how the Embedder has completely botched the display of the entire page. 
http://cmuems.com/2015c/dsfrank/10/16/jfbajsdbvak/
The student's original code works perfectly and without error:  http://cmuems.com/2015c/wp-content/uploads/2015/10/space.js

This is happening with several of my students, and causing them considerable stress. For example, Marisa spent a lot of time trying to figure out why her project wouldn't display in the blog: 
http://cmuems.com/2015c/marisal/10/16/aaagh-ran-out-of-time-project-landscape/ 
Here is a version of her code that I posted, where I replaced her && characters with nested if statements:  http://cmuems.com/2015c/admin/10/17/marisa-project-7-test-1/

**Comment by lmccart** [comment]
hi @golanlevin when you have time, could you please test this new version and let me know if it solves the problem?
http://cl.ly/2n1J1v2c2f1x

**Comment by golanlevin** [comment]
Hi Lauren, I'll test this today. THANK YOU SO MUCH for your help and care!

**Comment by golanlevin** [comment]
Hi Lauren, 
Everything works correctly now. Thank you so much for this fix; the issue can be closed. 
Please note that in my installation, I have also upgraded p5_iframe.html so that it uses 
     //cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.17/p5.min.js
instead of p5.js version 0.4.9. 
Thank you!!
Golan
